language: node_js

node_js:
  - "0.12"

before_install:
  - openssl aes-256-cbc -K $encrypted_3ba5678e770b_key -iv $encrypted_3ba5678e770b_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  - git config --global user.name "panjiabang"
  - git config --global user.email panjiabang@gmail.com
  - git clone -b master git@github.com:JamesPan/blog.jamespan.me.git .deploy_git && cd .deploy_git && git checkout gh-pages

install:
  - npm install --no-optional

script:
  - hexo clean
  - hexo g
  - hexo d