language: node_js

node_js:
  - "0.12"

branches:
  only:
    - master

git:
  submodules: false

addons:
  ssh_known_hosts:
  - github.com
  - blog-panjiabang.app.cnpaas.io

before_install:
  - openssl aes-256-cbc -K $encrypted_3ba5678e770b_key -iv $encrypted_3ba5678e770b_iv -in .travis/travis.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - git config --global user.name "panjiabang"
  - git config --global user.email panjiabang@gmail.com
  #- sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  #- git submodule update --init --recursive

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo clean
  - hexo g
  - hexo d
