# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: James Pan's Blog
subtitle: 代码猴子，计算机科学爱好者
description: 潘家邦的个人博客，关于技术、生活的思考和分享
author: 潘家邦
email: panjiabang@gmail.com
avatar: https://i.imgur.com/0DXtUTZb.jpg
author_title: 'Senior Code Monkey'
location: 'Hangzhou, China'
follow: https://twitter.com/_JamesPan_
language: en
github_repo: https://github.com/JamesPan/blog-src

stylus:
  compress: true

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.jamespan.me/
root: /
permalink: :year/:month/:day/:title/
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
permalink_defaults:

# Header
menu:
  Archive: /archives/
  Tag: /tags/
  Bullshit: /nonsense/
  About: /about/
  Pastime: /favorite/
  Exchange: /flea/

# Links
links:
  刘典的博客: http://blog.sina.com.cn/ld2254432
  StartupNews: http://news.dbanotes.net/news
  Cubernet's Blog: http://cubernet.cn
  屠城: https://www.haomwei.com

# Directory
source_dir: source
public_dir: public

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
auto_spacing: false # Add spaces between asian characters and western characters
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
post_asset_folder: false
relative_link: false
highlight:
  enable: false
  line_number: false
  tab_replace: true

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 2


apple_icon_57: //i.imgur.com/mV0lQ6M.jpg
apple_icon_72: //i.imgur.com/3D3m65B.jpg
apple_icon_76: //i.imgur.com/gg9PfXZ.jpg
apple_icon_114: //i.imgur.com/vak90qc.jpg
apple_icon_120: //i.imgur.com/RL6jkBf.jpg
apple_icon_152: //i.imgur.com/KWYY0nb.jpg


# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
server:
  port: 4000
  log: false
  ip: 0.0.0.0


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: MMM D YYYY
time_format: H:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

archive_generator:
  per_page: 15
  yearly: true
  monthly: false

# Disqus
disqus_shortname: jamespan
google_analytics: UA-64482504-1

# Extensions
## Plugins: https://github.com/hexojs/hexo/wiki/Plugins
## Themes: https://github.com/hexojs/hexo/wiki/Themes
theme: icarus
# theme: mewpassant


exclude_generator:

since: 2014

plugins:


markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: false
    linkify: false
    typographer: false
    quotes: '“”‘’'
  plugins:
    - markdown-it-footnote
    - markdown-it-sup
    - markdown-it-sub
  anchors:
    level: 1
    collisionSuffix: 'v'
    permalink: false
    permalinkClass: header-anchor
    permalinkSymbol: ''

html_minifier:
  exclude: 

image_stream:
  jquery: false

indicate_the_source:
  pattern: indicate-the-source
  enable: true
  render_engine: ejs
  element_class: indicate
  domain_white_list:
    - blog.jamespan.me
    - jamespan.me
    # - localhost
  template: "<blockquote><p>转载请注明出处：<%- post.permalink %></p><p>访问原文「<a href='<%- post.permalink %>'><%- post.title %></a>」获取最佳阅读体验并参与讨论</p></blockquote>"

asset_inline:
 enable: false

fancy_underline:
 enable: false
 underline_selectors:
   - ".article-entry a"
 exclude_selectors:
   - "p.article-more-link a"
 play_sound: true

#search:
#  path: search.xml
#  field: post

# widgets:
# - tag

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy: 
  type: git
  repo:
    github: git@github.com:JamesPan/blog.jamespan.me.git,gh-pages

