# Header
menu:
  #Home: /
  Archives: /archives/
  Tags: /tags/
  Timeline: /timeline/
  About: /about/
  Favorite: /favorite/
  Wiki: //wiki.jamespan.me/


# Content
excerpt_link: Read More
fancybox: true
profile: true
# Sidebar
sidebar: right
widgets:
- recent_posts
- links

thumbnail: true

# Links
links:
  并发编程网: http://ifeve.com/
  刘典的博客: http://blog.sina.com.cn/ld2254432
  StartupNews: http://news.dbanotes.net/news

# Contacts
contacts:
  github: http://github.com/JamesPan
  weibo: http://weibo.com/panjiabang
  twitter: https://twitter.com/_JamesPan_
  linkedin: https://cn.linkedin.com/pub/jiabang-pan/50/bb4/86
  rss: /atom.xml

google_analytics: UA-64482504-1
favicon: http://blog.jamespan.me/favicon.ico

wechat: http://ww4.sinaimg.cn/large/e724cbefgw1erjd7qc6xcj20b40b4myy.jpg

cnzz: 1000543904
recruit: true
default_thumbnail: http://ww1.sinaimg.cn/small/e724cbefgw1et25m6xn6ej20rs0rkjy4.jpg

# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:

